/**
 * Hardcoded values for report templates.
 * These values replace placeholders in the Docx templates
 * when not provided by the frontend.
 */
const hardcodedReportData = {
  // Course and Academic Details
  COURSE_CODE: "CSE301",
  CLASS: "Third Year CSE",
  ACADEMIC_YEAR: "2026-27",

  // Verification & Signatures
  VERIFIED_BY: "Department Verification",
  HOD_NAME: "Head of Department",

  // Final CO Attainments (CO1 to CO6)
  FINAL_CO1_ATTAINMENT: "75%",
  FINAL_CO2_ATTAINMENT: "80%",
  FINAL_CO3_ATTAINMENT: "70%",
  FINAL_CO4_ATTAINMENT: "85%",
  FINAL_CO5_ATTAINMENT: "78%",
  FINAL_CO6_ATTAINMENT: "82%",

  // Course Exit Survey (CES) for CO1 - CO6
  CES_CO1_70: "65%",
  CES_CO1_5570: "25%",
  CES_CO1_55: "10%",
  CES_CO1_ATTAINMENTOUTOF3: "2.6",

  CES_CO2_70: "68%",
  CES_CO2_5570: "22%",
  CES_CO2_55: "10%",
  CES_CO2_ATTAINMENTOUTOF3: "2.7",

  CES_CO3_70: "60%",
  CES_CO3_5570: "30%",
  CES_CO3_55: "10%",
  CES_CO3_ATTAINMENTOUTOF3: "2.5",

  CES_CO4_70: "72%",
  CES_CO4_5570: "20%",
  CES_CO4_55: "8%",
  CES_CO4_ATTAINMENTOUTOF3: "2.8",

  CES_CO5_70: "64%",
  CES_CO5_5570: "26%",
  CES_CO5_55: "10%",
  CES_CO5_ATTAINMENTOUTOF3: "2.6",

  CES_CO6_70: "70%",
  CES_CO6_5570: "20%",
  CES_CO6_55: "10%",
  CES_CO6_ATTAINMENTOUTOF3: "2.7",

  // Theory Assessment - CA1 (Continuous Assessment 1: CO1 - CO3)
  CA1_STUDENTSSCORINGMORETHAN50MARKS_CO1: "82%",
  CA1_STUDENTSSCORINGMORETHAN50MARKS_CO2: "80%",
  CA1_STUDENTSSCORINGMORETHAN50MARKS_CO3: "75%",
  CA1_ATTAINMENTLEVEL_CO1: "3",
  CA1_ATTAINMENTLEVEL_CO2: "3",
  CA1_ATTAINMENTLEVEL_CO3: "2.5",
  CA1_ATTAINMENTLEVELS_CO: "3",
  CA1_ATTAINMENTLEVELS_CO2: "3",

  // Theory Assessment - MSE (Mid Semester Examination: CO1 - CO3)
  MSE_STUDENTSSCORINGMORETHAN50MARKS_CO1: "78%",
  MSE_STUDENTSSCORINGMORETHAN50MARKS_CO2: "82%",
  MSE_STUDENTSSCORINGMORETHAN50MARKS_CO3: "74%",
  MSE_ATTAINMENTLEVEL_CO1: "2.5",
  MSE_ATTAINMENTLEVEL_CO2: "3",
  MSE_ATTAINMENTLEVEL_CO3: "2.5",
  MSE_ATTAINMENTLEVELS_CO: "2.5",
  MSE_ATTAINMENTLEVELS_CO2: "2.5",

  // Theory Assessment - CA2 (Continuous Assessment 2: CO4 - CO6)
  CA2_STUDENTSSCORINGMORETHAN50MARKS_CO4: "85%",
  CA2_STUDENTSSCORINGMORETHAN50MARKS_CO5: "79%",
  CA2_STUDENTSSCORINGMORETHAN50MARKS_CO6: "84%",
  CA2_ATTAINMENTLEVEL_CO4: "3",
  CA2_ATTAINMENTLEVEL_CO5: "2.5",
  CA2_ATTAINMENTLEVEL_CO6: "3",
  CA2_ATTAINMENTLEVELS_CO: "3",
  CA2_ATTAINMENTLEVELS_CO5: "3",

  // Theory Assessment - ESE (End Semester Examination)
  ESE_STUDENTSSCORINGMORETHAN50MARKS_ANALYSISSUMMARYANDATTAINMENT: "80%",
  ESE_ATTAINMENTLEVEL_ANALYSISSUMMARYANDATTAINMENT: "3",
  ESE_ATTAINMENTLEVELS_ANALYSISSUMMARYANDATTAINMENT: "3",

  // Laboratory Assessment (Continuous Assessment CA1 & CA2: CO1 - CO3)
  CA1_CA2_CO1_OFSTUDENTSSECUREMORETHANSETLEVEL: "84%",
  CA1_CA2_CO1_ATTAINMENT: "3",
  CA1_CA2_CO2_OFSTUDENTSSECUREMORETHANSETLEVEL: "86%",
  CA1_CA2_CO2_ATTAINMENT: "3",
  CA1_CA2_CO3_OFSTUDENTSSECUREMORETHANSETLEVEL: "80%",
  CA1_CA2_CO3_ATTAINMENT: "3",

  // Laboratory with PR/OR - ESE
  ESE_STUDENTSSCORINGMORETHAN40MARKS_ANALYSISSUMMARYANDATTAINMENT: "82%",
};

module.exports = { hardcodedReportData };
